"""empty message

Revision ID: 273bb7575e24
Revises: 91811f12da39
Create Date: 2018-10-29 17:21:41.248003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273bb7575e24'
down_revision = '91811f12da39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_file', sa.Column('origin_path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_file', 'origin_path')
    # ### end Alembic commands ###
