"""empty message

Revision ID: 2ca771823775
Revises: 2e1d85113b0a
Create Date: 2018-10-29 16:26:41.074252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca771823775'
down_revision = '2e1d85113b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('font_user', sa.Column('join_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('font_user', 'join_time')
    # ### end Alembic commands ###
