"""empty message

Revision ID: 2e1d85113b0a
Revises: 
Create Date: 2018-10-29 14:55:46.836680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1d85113b0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_font_user_email'), 'font_user', ['email'], unique=True)
    op.create_index(op.f('ix_font_user_username'), 'font_user', ['username'], unique=False)
    op.create_table('instance_file',
    sa.Column('fid', sa.String(length=32), nullable=False),
    sa.Column('fmd5', sa.String(length=32), nullable=False),
    sa.Column('server_path', sa.String(length=256), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fid'),
    sa.UniqueConstraint('fmd5')
    )
    op.create_table('virtual_file',
    sa.Column('vid', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('fmd5', sa.String(length=32), nullable=False),
    sa.Column('client_path', sa.Text(), nullable=False),
    sa.Column('server_path', sa.String(length=256), nullable=False),
    sa.Column('font_file_name', sa.String(length=256), nullable=False),
    sa.Column('server_filename', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instance_file.fid'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['font_user.id'], ),
    sa.PrimaryKeyConstraint('vid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_file')
    op.drop_table('instance_file')
    op.drop_index(op.f('ix_font_user_username'), table_name='font_user')
    op.drop_index(op.f('ix_font_user_email'), table_name='font_user')
    op.drop_table('font_user')
    # ### end Alembic commands ###
