"""empty message

Revision ID: 91811f12da39
Revises: 2ca771823775
Create Date: 2018-10-29 16:37:57.402586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91811f12da39'
down_revision = '2ca771823775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('share_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('from_person_id', sa.String(length=64), nullable=False),
    sa.Column('from_person_name', sa.String(length=64), nullable=False),
    sa.Column('to_person_id', sa.String(length=64), nullable=False),
    sa.Column('to_person_name', sa.String(length=64), nullable=False),
    sa.Column('share_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('share_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    # ### end Alembic commands ###
